config/routes.rb
Rails.application.routes.draw do

devise_for :users
root to: 'pages#home'
get "my_house", to: "houses#show"
get 'users/onboard', to: "users#onboard", as: :onboard
resources :users, only: [:show, :edit, :update]
resources :whiteboard_messages, only: [:new, :create, :destroy]
resources :room_chores, only: [:show, :edit, :update] # show will be partial displayed on homepage
resources :chores, only: [:index]
resources :amenities, only: [:index] do
  resources :bookings, only: [:new, :create, :destroy]
end
post 'line/webhook', to: "line/bot#receive"

# namespace :admin do
  # resources :chores
  # resources :amenities
  # resources :rooms, only: [:new, :create, :edit, :update, :destroy]
  # auto create :room_chores?
# end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  def show
    if current_user.room.nil?
      current_user.room = Room.last
    end
    @room_chores = current_user.room.room_chores

    @whiteboard_message = WhiteboardMessage.new
    @messages = WhiteboardMessage.last(10)
    @amenities = Amenity.all

    @current_room_chore = current_user.current_room_chore
    @previous_room_chore = current_user.previous_room_chore
    @next_room_chore = current_user.next_room_chore

    @booking = Booking.new
    @user = User.find_by(id: params[:id])
    @users = User.all
  end
end

app/views/houses/show.html.erb
<div class="container-fluid" style="padding: 0 0;">
  <div class="meguro-div">
    <!-- Button trigger modal -->
<!--     <button style="position: absolute;bottom: 0; right: 0; font-size: 36px;" data-toggle="modal" data-target="#lineModal"><i class="fab fa-line" style="color:green"></i></button>
 -->    <div class="show-banner d-flex flex-column justify-content-center">
      <div class="meguro-container d-flex justify-content-end pr-2">
        <p>
          <% if Time.zone.now >= Time.zone.parse("0:01") && Time.zone.now <= Time.zone.parse("12:00") %>
            <i class="fas fa-coffee mr-2" style="color:#4B371B"></i>Good Morning, <%= current_user.first_name %>
          <% elsif Time.zone.now >= Time.zone.parse("12:01") && Time.zone.now <= Time.zone.parse("17:00") %>
            <i class="fas fa-sun mr-2" style="color:#f9cd1b"></i>Good Afternoon, <%= current_user.first_name %>
          <% else %>
            <i class="fas fa-cloud-moon mr-2"></i>Good Evening, <%= current_user.first_name %>
          <% end %>
        </p>
      </div>
      <div class='mb-4'>
        <h2 style="font-family: Nova Square; font-size: 48px;">Meguro Mansion</h2>
      </div>
      <div class="house-members-container container-fluid">
        <% @users.each do |user| %>
          <div class="d-flex flex-column text-center mt-5">
            <%= link_to user_path(user), class: "avatar-opacity" do  %>
              <i><%= cl_image_tag user.image.key, class: "avatarmem" %></i>
              <div class="member-name my-2">
                <%= user.first_name %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <% unless current_user.onboarded %>
    <div class="line-onboarding container-fluid animated fadeIn">
      Welcome <%= current_user.first_name %> to Meguro Mansion! Don't forget to <a class="btn btn-outline-light" data-toggle="modal" data-target="#lineModal">JOIN</a> the house line group 😎.
    </div>
  <% end %>

<!-- <div class="members-header text-center mt-4">
  <h2>Mansioners</h2>
</div> -->


<div class="container mt-5">

  <div class="row justify-content-center my-3">
    <div class="col-12">
      <div class="whiteboard-card">
        <div class="card-header text-center">
          <h3>Whiteboard</h3>
        </div>
        <div class="card-body">
          <%= render 'whiteboard_messages/index', whiteboard_message: @whiteboard_message %>
        </div>
      </div>
    </div>
  </div>

  <hr>

  <div class="row justify-content-center my-3">
    <div class="col-12">
      <div class="card wide-container">
        <div class="card-header text-center">
          <h3>Your Chores</h3>
        </div>
        <div class="card-body" id="chores">

          <div class="d-flex justify-content-around">
            <div>
              <a href="chores" class="card-link">
                <div class="other-week border p-3 d-flex flex-column" style="color: black;">
                  <p class="mr-3"><strong>Last Week:</strong></p>
                   <% if @previous_room_chore.status %>
                    <p class="mr-3"><%= @previous_room_chore.chore.name %>
                      <i class="far fa-check-circle mr-2" style="color:#1EDD88;"></i>
                    </p>
                   <% else %>
                   <p class="mr-3"><%= @previous_room_chore.chore.name %>
                    <i class="far fa-circle mr-2" style="color:#FD1015;"></i>
                  </p>
                   <% end %>
                </div>
              </a>
            </div>

            <div>
              <a href="chores" class="card-link">
                <div class="this-week border p-3 d-flex flex-column justify-content-around" style='color: black; height: 100%;'>
                  <h4><%= @current_room_chore.formatted_start_date %> - <%= @current_room_chore.formatted_end_date %></h4>
                  <div class="this-week-info">
                    <%= @current_room_chore.chore.name %>
                    <% if @current_room_chore.status %>
                      <i class="far fa-check-circle mr-2" style="color:#1EDD88;"></i>
                    <% else %>
                      <i class="far fa-circle mr-2" style="color:#FD1015;"></i>
                    <% end %>
                  </div>
                </div>
              </a>
            </div>

            <div>
              <a href="chores" class="card-link">
                <div class="other-week border p-3 d-flex flex-column" style="color: black;">
                  <p class="mr-3"><strong>Next Week:</strong></p>
                  <% if @next_room_chore.status %>
                    <p class='mr-3'><%= @next_room_chore.chore.name %>
                      <i class="far fa-check-circle mr-2" style="color:#1EDD88;"></i>
                    </p>
                   <% else %>
                  <p class="mr-3"><%= @next_room_chore.chore.name %>
                    <i class="far fa-circle mr-2" style="color:#FD1015;"></i>
                  </p>
                  <% end %>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <hr>

  <div class="row justify-content-center my-3">
    <div class="col-12">
      <div class="card wide-container">
        <div class="card-header text-center">
          <h3>Amenities</h3>
        </div>
        <div class="card-body">
          <%= render "amenities/summary" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row justify-content-center my-3">
    <div class="col-12">
      <div class="card wide-container">
        <div class="card-header text-center">
          <h3>Map</h3>
        </div>
        <div class="card-body">
          <iframe src="https://www.google.com/maps/d/embed?mid=1XqreEWk5L-esoXyiEMNx8ZUfJYBUsZOO" width="100%" height="480"></iframe></iframe>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="lineModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-center" style="text-align: center" id="exampleModalLabel">Add us on <i class="fab fa-line" style="color:green; font-size: 32px;"></i></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= image_tag "Group-QR.jpg", alt: "alttext", style: "width: 100%" %>
      </div>
    </div>
  </div>
  <%= simple_form_for :onboard, url: onboard_path, remote: true, method: :get, id: "submit-onboard" do |f| %>
  <% end %>
</div>