config/routes.rb
Rails.application.routes.draw do

devise_for :users
root to: 'pages#home'
get "my_house", to: "houses#show"
get 'users/onboard', to: "users#onboard", as: :onboard
resources :users, only: [:show, :edit, :update]
resources :whiteboard_messages, only: [:new, :create, :destroy]
resources :room_chores, only: [:show, :edit, :update] # show will be partial displayed on homepage
resources :chores, only: [:index]
resources :amenities, only: [:index] do
  resources :bookings, only: [:new, :create, :destroy]
end
post 'line/webhook', to: "line/bot#receive"

# namespace :admin do
  # resources :chores
  # resources :amenities
  # resources :rooms, only: [:new, :create, :edit, :update, :destroy]
  # auto create :room_chores?
# end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
   <p>made with <i class="fas fa-heart"></i> by Relief Team at Le Wagon</p>
  </div>
</div>
</body>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to my_house_path, class: "navbar-brand" do %>
    <%= image_tag "app_logo.png", class: "logo" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <% if current_user.image.attached?%>
          <%= cl_image_tag current_user.image.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= image_tag "user_photo.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
         </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link text-white" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>