config/routes.rb
Rails.application.routes.draw do

devise_for :users
root to: 'pages#home'
get "my_house", to: "houses#show"
get 'users/onboard', to: "users#onboard", as: :onboard
resources :users, only: [:show, :edit, :update]
resources :whiteboard_messages, only: [:new, :create, :destroy]
resources :room_chores, only: [:show, :edit, :update] # show will be partial displayed on homepage
resources :chores, only: [:index]
resources :amenities, only: [:index] do
  resources :bookings, only: [:new, :create, :destroy]
end
post 'line/webhook', to: "line/bot#receive"

# namespace :admin do
  # resources :chores
  # resources :amenities
  # resources :rooms, only: [:new, :create, :edit, :update, :destroy]
  # auto create :room_chores?
# end
end

app/models/whiteboard_message.rb
class WhiteboardMessage < ApplicationRecord

  default_scope { order(created_at: :desc) }

  validates :message, presence: true
  has_one_attached :image
  belongs_to :user
end

app/controllers/whiteboard_messages_controller.rb
class WhiteboardMessagesController < ApplicationController

  def create
    @messages = WhiteboardMessage.all
    @whiteboard_message = WhiteboardMessage.new(whiteboard_messages_params)
    @whiteboard_message.user = current_user
    if @whiteboard_message.save
      respond_to do |format|
        format.html { redirect_to my_house_path }
        format.js
      end
    else
      respond_to do |format|
        format.html { render "houses/show" }
        format.js
      end
    end
  end

  def destroy
    @whiteboard_message = WhiteboardMessage.find(params[:id])
    if @whiteboard_message.delete
      respond_to do |format|
        format.html { redirect_to my_house_path }
        format.js
      end
    end
  end

  private

  def whiteboard_messages_params
    params.require(:whiteboard_message).permit(:message, :image)
  end

end

app/views/whiteboard_messages/_form.html.erb
<%= simple_form_for(message, remote: true) do |f| %>
<div class="d-flex">
  <div class="whiteboard-avatar-fill flex-grow-0">

    <%#= image_tag "user_photo.jpg", alt: "User Avatar", class: "avatar post-avatar" %>
    <%= cl_image_tag current_user.image.key, alt: "alttext", class: "border avatarlg" %>
  </div>
  <%= f.input :message, input_html: { class: "post_message" }, wrapper_html: { class: 'flex-grow-1' }, placeholder: "Post a message", label: false %>
</div>
    <%= f.input :image, label: false, input_html: { class: "post_picture" } %>
    <%= f.submit "Submit", class: "btn btn-dark post_picture"  %>
<% end %>

app/views/whiteboard_messages/_index.html.erb
<ul class="whiteboard-container">
  <div id='adjacent-message-div'></div>
  <% @messages.each do |message|%>
    <%= render 'whiteboard_messages/message_card', message: message %>
  <% end %>
</ul>

<div class="whiteboard-form">
  <%= render 'whiteboard_messages/form', message: WhiteboardMessage.new %>
</div>

app/views/whiteboard_messages/_message_card.html.erb
<div class="whiteboard-message" id="message-<%= raw message.id %>">
  <% if message && message.user %>
    <%= cl_image_tag message.user.image.key, alt: "alttext", class: "avatarlg" %>
  <% end %>
  <div class="whiteboard-message-content">
      <p><small><%= message.created_at.strftime("%b %d, %I:%M %p") %></small></p>
      <p><%= message.message %></p>
      <% if message.image.attached? %>
        <%= cl_image_tag(message.image.key, crop: :fill) %>
      <% end %>
  </div>
  <div class="whiteboard-message-actions">
    <% if message.user == current_user %>
      <%= link_to whiteboard_message_path(message), method: :delete, remote: true do %>
        <i class="far fa-trash-alt"></i>
      <% end %>

    <% end %>
  </div>

</div>

app/views/whiteboard_messages/create.js.erb
function appendMessage(innerHTML) {
  var topMessage = document.querySelector("#adjacent-message-div");
  topMessage.insertAdjacentHTML("afterend", innerHTML);
}

function refreshForm(innerHTML) {
  var formContainer = document.querySelector(".whiteboard-form");
  formContainer.innerHTML = innerHTML;
}

<% if @whiteboard_message.errors.any? %>
  refreshForm("<%= j render 'form', message: Message.new %>");
<% else %>
  appendMessage("<%= j render 'message_card', message: @whiteboard_message %>");
  refreshForm("<%= j render 'form', message: WhiteboardMessage.new %>");
<% end %>

app/views/whiteboard_messages/destroy.js.erb
function deleteMessage(id) {
  document.querySelector(`#message-${id}`).remove();
}

<% if @whiteboard_message.errors.any? %>
<% else %>
  deleteMessage("<%= raw @whiteboard_message.id %>");
<% end %>